services:
  dbserver:
    image: postgres:12
    environment:
      - "POSTGRES_DB=SysAccess"
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
    ports:
      - "5432:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "/usr/bin/pg_isready", "--dbname=SysAccess"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - internal
      
  wildfly:
    build:
      target: deployed
      context: .
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      dbserver:
        condition: service_healthy
    networks:
      - internal

volumes:
  db_data:

networks:
  internal: